// Original file: src/framework/protobuf/org.silastandard/ParameterConstraintProvider.proto

import type * as grpc from '@grpc/grpc-js'
import type { MethodDefinition } from '@grpc/proto-loader'
import type { Subscribe_ParametersConstraints_Parameters as _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters, Subscribe_ParametersConstraints_Parameters__Output as _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/parameterconstraintsprovider/v1/Subscribe_ParametersConstraints_Parameters';
import type { Subscribe_ParametersConstraints_Responses as _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses, Subscribe_ParametersConstraints_Responses__Output as _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses__Output } from '../../../../../../sila2/org/silastandard/core/parameterconstraintsprovider/v1/Subscribe_ParametersConstraints_Responses';

export interface ParameterConstraintsProviderClient extends grpc.Client {
  Subscribe_ParametersConstraints(argument: _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters, metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<_sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses__Output>;
  Subscribe_ParametersConstraints(argument: _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters, options?: grpc.CallOptions): grpc.ClientReadableStream<_sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses__Output>;
  subscribeParametersConstraints(argument: _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters, metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<_sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses__Output>;
  subscribeParametersConstraints(argument: _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters, options?: grpc.CallOptions): grpc.ClientReadableStream<_sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses__Output>;

}

export interface ParameterConstraintsProviderHandlers extends grpc.UntypedServiceImplementation {
  Subscribe_ParametersConstraints: grpc.handleServerStreamingCall<_sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters__Output, _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses>;

}

export interface ParameterConstraintsProviderDefinition extends grpc.ServiceDefinition {
  Subscribe_ParametersConstraints: MethodDefinition<_sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters, _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses, _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Parameters__Output, _sila2_org_silastandard_core_parameterconstraintsprovider_v1_Subscribe_ParametersConstraints_Responses__Output>
}
