// Original file: src/framework/protobuf/org.silastandard/AuthorizationService.proto

import type * as grpc from '@grpc/grpc-js'
import type { MethodDefinition } from '@grpc/proto-loader'
import type { Get_FCPAffectedByMetadata_AccessToken_Parameters as _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, Get_FCPAffectedByMetadata_AccessToken_Parameters__Output as _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/authorizationservice/v1/Get_FCPAffectedByMetadata_AccessToken_Parameters';
import type { Get_FCPAffectedByMetadata_AccessToken_Responses as _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses, Get_FCPAffectedByMetadata_AccessToken_Responses__Output as _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output } from '../../../../../../sila2/org/silastandard/core/authorizationservice/v1/Get_FCPAffectedByMetadata_AccessToken_Responses';

export interface AuthorizationServiceClient extends grpc.Client {
  Get_FCPAffectedByMetadata_AccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_FCPAffectedByMetadata_AccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_FCPAffectedByMetadata_AccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_FCPAffectedByMetadata_AccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataAccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataAccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataAccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataAccessToken(argument: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output) => void): grpc.ClientUnaryCall;

}

export interface AuthorizationServiceHandlers extends grpc.UntypedServiceImplementation {
  Get_FCPAffectedByMetadata_AccessToken: grpc.handleUnaryCall<_sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters__Output, _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses>;

}

export interface AuthorizationServiceDefinition extends grpc.ServiceDefinition {
  Get_FCPAffectedByMetadata_AccessToken: MethodDefinition<_sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters, _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses, _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Parameters__Output, _sila2_org_silastandard_core_authorizationservice_v1_Get_FCPAffectedByMetadata_AccessToken_Responses__Output>
}
