// Original file: src/framework/protobuf/org.silastandard/LockController.proto

import type * as grpc from '@grpc/grpc-js'
import type { MethodDefinition } from '@grpc/proto-loader'
import type { Get_FCPAffectedByMetadata_LockIdentifier_Parameters as _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, Get_FCPAffectedByMetadata_LockIdentifier_Parameters__Output as _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/Get_FCPAffectedByMetadata_LockIdentifier_Parameters';
import type { Get_FCPAffectedByMetadata_LockIdentifier_Responses as _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses, Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output as _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/Get_FCPAffectedByMetadata_LockIdentifier_Responses';
import type { Get_IsLocked_Parameters as _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, Get_IsLocked_Parameters__Output as _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/Get_IsLocked_Parameters';
import type { Get_IsLocked_Responses as _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses, Get_IsLocked_Responses__Output as _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/Get_IsLocked_Responses';
import type { LockServer_Parameters as _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, LockServer_Parameters__Output as _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/LockServer_Parameters';
import type { LockServer_Responses as _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses, LockServer_Responses__Output as _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/LockServer_Responses';
import type { UnlockServer_Parameters as _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, UnlockServer_Parameters__Output as _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/UnlockServer_Parameters';
import type { UnlockServer_Responses as _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses, UnlockServer_Responses__Output as _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output } from '../../../../../../sila2/org/silastandard/core/lockcontroller/v1/UnlockServer_Responses';

export interface LockControllerClient extends grpc.Client {
  Get_FCPAffectedByMetadata_LockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_FCPAffectedByMetadata_LockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_FCPAffectedByMetadata_LockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_FCPAffectedByMetadata_LockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataLockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataLockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataLockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;
  getFcpAffectedByMetadataLockIdentifier(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output) => void): grpc.ClientUnaryCall;

  Get_IsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_IsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_IsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_IsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  getIsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  getIsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  getIsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;
  getIsLocked(argument: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output) => void): grpc.ClientUnaryCall;

  LockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  LockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  LockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  LockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  lockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  lockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  lockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  lockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output) => void): grpc.ClientUnaryCall;

  UnlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  UnlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  UnlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  UnlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  unlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  unlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  unlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;
  unlockServer(argument: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output) => void): grpc.ClientUnaryCall;

}

export interface LockControllerHandlers extends grpc.UntypedServiceImplementation {
  Get_FCPAffectedByMetadata_LockIdentifier: grpc.handleUnaryCall<_sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses>;

  Get_IsLocked: grpc.handleUnaryCall<_sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses>;

  LockServer: grpc.handleUnaryCall<_sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses>;

  UnlockServer: grpc.handleUnaryCall<_sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses>;

}

export interface LockControllerDefinition extends grpc.ServiceDefinition {
  Get_FCPAffectedByMetadata_LockIdentifier: MethodDefinition<_sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters, _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses, _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_Get_FCPAffectedByMetadata_LockIdentifier_Responses__Output>
  Get_IsLocked: MethodDefinition<_sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters, _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses, _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_Get_IsLocked_Responses__Output>
  LockServer: MethodDefinition<_sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters, _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses, _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_LockServer_Responses__Output>
  UnlockServer: MethodDefinition<_sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters, _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses, _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Parameters__Output, _sila2_org_silastandard_core_lockcontroller_v1_UnlockServer_Responses__Output>
}
