// Original file: src/framework/protobuf/org.silastandard/SimulationController.proto

import type * as grpc from '@grpc/grpc-js'
import type { MethodDefinition } from '@grpc/proto-loader'
import type { Get_SimulationMode_Parameters as _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, Get_SimulationMode_Parameters__Output as _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/simulationcontroller/v1/Get_SimulationMode_Parameters';
import type { Get_SimulationMode_Responses as _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses, Get_SimulationMode_Responses__Output as _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output } from '../../../../../../sila2/org/silastandard/core/simulationcontroller/v1/Get_SimulationMode_Responses';
import type { StartRealMode_Parameters as _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, StartRealMode_Parameters__Output as _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/simulationcontroller/v1/StartRealMode_Parameters';
import type { StartRealMode_Responses as _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses, StartRealMode_Responses__Output as _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output } from '../../../../../../sila2/org/silastandard/core/simulationcontroller/v1/StartRealMode_Responses';
import type { StartSimulationMode_Parameters as _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, StartSimulationMode_Parameters__Output as _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters__Output } from '../../../../../../sila2/org/silastandard/core/simulationcontroller/v1/StartSimulationMode_Parameters';
import type { StartSimulationMode_Responses as _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses, StartSimulationMode_Responses__Output as _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output } from '../../../../../../sila2/org/silastandard/core/simulationcontroller/v1/StartSimulationMode_Responses';

export interface SimulationControllerClient extends grpc.Client {
  Get_SimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_SimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_SimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  Get_SimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  getSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  getSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  getSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  getSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;

  StartRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  StartRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  StartRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  StartRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startRealMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output) => void): grpc.ClientUnaryCall;

  StartSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  StartSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  StartSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  StartSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;
  startSimulationMode(argument: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, callback: (error?: grpc.ServiceError, result?: _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output) => void): grpc.ClientUnaryCall;

}

export interface SimulationControllerHandlers extends grpc.UntypedServiceImplementation {
  Get_SimulationMode: grpc.handleUnaryCall<_sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters__Output, _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses>;

  StartRealMode: grpc.handleUnaryCall<_sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters__Output, _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses>;

  StartSimulationMode: grpc.handleUnaryCall<_sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters__Output, _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses>;

}

export interface SimulationControllerDefinition extends grpc.ServiceDefinition {
  Get_SimulationMode: MethodDefinition<_sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters, _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses, _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Parameters__Output, _sila2_org_silastandard_core_simulationcontroller_v1_Get_SimulationMode_Responses__Output>
  StartRealMode: MethodDefinition<_sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters, _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses, _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Parameters__Output, _sila2_org_silastandard_core_simulationcontroller_v1_StartRealMode_Responses__Output>
  StartSimulationMode: MethodDefinition<_sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters, _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses, _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Parameters__Output, _sila2_org_silastandard_core_simulationcontroller_v1_StartSimulationMode_Responses__Output>
}
